### ISSUE TITLE
The parameter "optional" don't work on AddEncryptedJsonFile()

### ISSUE THREAD

**Issue by jbastarie** [am-creations/Configuration.EncryptedJson#1]
the parameter "optional" don't work on AddEncryptedJsonFile() :

example :
`var certificateLoader = new FilesystemCertificateLoader(certLocation);
config.AddEncryptedJsonFile("[...]\\appsettings.Encrypted.json", true, certificateLoader);`

exception : 
`System.IO.FileNotFoundException: Could not find file '[...]\appsettings.Encrypted.json'.
File name: '[...]\appsettings.Encrypted.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at AmCreations.Configuration.EncryptedJson.EncryptedJsonConfigurationFileParser.ParseStream(String path)
   at AmCreations.Configuration.EncryptedJson.EncryptedJsonConfigurationFileParser.Parse(String path, ICrypter crypter)
   at AmCreations.Configuration.EncryptedJson.EncryptedJsonConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at [...].Program.Main(String[] args) in [...]\Program.cs:line 12`

**Comment by PhenX** [comment]
Fixed by https://github.com/am-creations/Configuration.EncryptedJson/commit/38b41bd6ea7d7c62be2f948886b5e0476072f251
